In [49]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [50]:
data = pd.read_csv(r"C:\Users\hc749\Downloads\1768299091977-ML Linear Regression Home Price Prediction & Analysis Project  Resource16932049360.txt")

In [51]:
pd.set_option("display.max_columns",None)

In [52]:
data.head(2)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,03/09/2016,2.5,3067.0,2.0,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,03/12/2016,2.5,3067.0,2.0,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0

In [53]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34857 entries, 0 to 34856
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         34857 non-null  object
 1   Address        34857 non-null  object
 2   Rooms          34857 non-null  int64
 3   Type           34857 non-null  object
 4   Price          27247 non-null  float64
 5   Method         34857 non-null  object
 6   SellerG        34857 non-null  object
 7   Date           34857 non-null  object
 8   Distance       34856 non-null  float64
 9   Postcode       34856 non-null  float64
 10  Bedroom2       26640 non-null  float64
 11  Bathroom       26631 non-null  float64
 12  Car            26129 non-null  float64
 13  Landsize       23047 non-null  float64
 14  BuildingArea   13742 non-null  float64
 15  YearBuilt      15551 non-null  float64
 16  CouncilArea    34854 non-null  object
 17  Lattitude      26881 non-null  float64
 18  Longtitude     26881 non-null  float64
 19  Regionname     34854 non-null  object
 20  Propertycount  34854 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 5.6+ MB

In [54]:
data.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,34857.000000,2.724700e+04,34856.000000,34856.000000,26640.000000,26631.000000,26129.000000,23047.000000,13742.00000,15551.000000,26881.000000,26881.000000,34854.000000
mean,3.031012,1.050173e+06,11.184929,3116.062859,3.084647,1.624798,1.728845,593.598993,160.25640,1965.289885,-37.810634,145.001851,7572.888306
std,0.969933,6.414671e+05,6.788892,109.023903,0.980690,0.724212,1.010771,3398.841946,401.26706,37.328178,0.090279,0.120169,4428.090313
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1196.000000,-38.190430,144.423790,83.000000
25%,2.000000,6.350000e+05,6.400000,3051.000000,2.000000,1.000000,1.000000,224.000000,102.00000,1940.000000,-37.862950,144.933500,4385.000000
50%,3.000000,8.700000e+05,10.300000,3103.000000,3.000000,2.000000,2.000000,521.000000,136.00000,1970.000000,-37.807600,145.007800,6763.000000
75%,4.000000,1.295000e+06,14.000000,3156.000000,4.000000,2.000000,2.000000,670.000000,188.00000,2000.000000,-37.754100,145.071900,10412.000000
max,16.000000,1.120000e+07,48.100000,3978.000000,30.000000,12.000000,26.000000,433014.000000,44515.00000,2106.000000,-37.390200,145.526350,21650.000000

In [55]:
data.drop(["Address","Date","Postcode","YearBuilt","Lattitude","Longtitude"],axis =1,inplace =True)

In [56]:
data.head(2)

,Suburb,Rooms,Type,Price,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Regionname,Propertycount
0,Abbotsford,2,h,NaN,SS,Jellis,2.5,2.0,1.0,1.0,126.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
1,Abbotsford,2,h,1480000.0,S,Biggin,2.5,2.0,1.0,1.0,202.0,NaN,Yarra City Council,Northern Metropolitan,4019.0

In [57]:
data.isnull().sum()

Suburb               0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Distance             1
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
CouncilArea          3
Regionname           3
Propertycount        3
dtype: int64

In [58]:
data["Distance"].fillna(0,inplace=True)
data["Bedroom2"].fillna(0,inplace=True)
data["Bathroom"].fillna(0,inplace=True)
data["Car"].fillna(0,inplace=True)
data["Propertycount"].fillna(0,inplace=True)

In [62]:
data.fillna(data[["Landsize","BuildingArea"]].mean(),inplace=True)

In [67]:
data.dropna(inplace=True,ignore_index=True)

In [68]:
data.isnull().sum()

Suburb           0
Rooms            0
Type             0
Price            0
Method           0
SellerG          0
Distance         0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
CouncilArea      0
Regionname       0
Propertycount    0
dtype: int64

In [69]:
data["Method"].unique()

array(['S', 'SP', 'PI', 'VB', 'SA'], dtype=object)

In [71]:
data.select_dtypes(include = object)

,Suburb,Type,Method,SellerG,CouncilArea,Regionname
0,Abbotsford,h,S,Biggin,Yarra City Council,Northern Metropolitan
1,Abbotsford,h,S,Biggin,Yarra City Council,Northern Metropolitan
2,Abbotsford,h,SP,Biggin,Yarra City Council,Northern Metropolitan
3,Abbotsford,h,PI,Biggin,Yarra City Council,Northern Metropolitan
4,Abbotsford,h,VB,Nelson,Yarra City Council,Northern Metropolitan
...,...,...,...,...,...,...
27239,Yarraville,h,PI,Jas,Maribyrnong City Council,Western Metropolitan
27240,Yarraville,h,SP,Sweeney,Maribyrnong City Council,Western Metropolitan
27241,Yarraville,t,S,Jas,Maribyrnong City Council,Western Metropolitan
27242,Yarraville,h,SP,hockingstuart,Maribyrnong City Council,Western Metropolitan
27243,Yarraville,h,PI,RW,Maribyrnong City Council,Western Metropolitan

In [75]:
data=pd.get_dummies(data,columns=["Method"])

In [76]:
data=pd.get_dummies(data,columns=["Suburb"])

In [80]:
data=pd.get_dummies(data,columns=["Type","SellerG","CouncilArea","Regionname"])

In [86]:
x=data.drop("Price",axis=1)
y=data["Price"]

In [87]:
from sklearn.model_selection import train_test_split

In [177]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [178]:
from sklearn.linear_model import LinearRegression

In [179]:
model = LinearRegression()

In [180]:
model.fit(x_train,y_train)

LinearRegression()

In [181]:
yp=model.predict(x_test)

In [187]:
from sklearn.metrics import r2_score,root_mean_squared_error,mean_absolute_error,mean_squared_error

In [188]:
r2_score(yp,y_test)

0.5327628986395907

In [189]:
root_mean_squared_error(yp,y_test)

367776.7921588255

In [190]:
model.score(x_train,y_train)

0.6746078592844227

In [191]:
model.score(x_test,y_test)

0.6714657044005963

In [192]:
mean_absolute_error(yp,y_test)

234922.3642671803

In [193]:
mean_squared_error(yp,y_test)

135259768850.63593